# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: linkedin_auth_dev
  user: postgres
  pass:

test:
  adapter: postgresql
  database: linkedin_auth_dev
  user: postgres
  pass:

production:
  adapter: postgresql
  database: linkedin_auth
  user: postgres
  pass:
